### PR TITLE
Implementing visitorCallback and improving tests

### PR DESCRIPTION
**Pull request by IsabellaCerbino**
I created a callback function to be called when the diff is applied, that is useful to create the possibility to do something with the object that was changed by the diff apply. In my case i create a visitor pattern to find what objects were changed in the apply process, with a callback like the follow

``` javascript
var visitorDiffCallback = function(val){
    val['__isVisited'] = true;
};
diff.applyDiff(obj, diffs, visitorDiffCallback);
```

this parameter is optional and all the old features keep working like before.

### CODE REVIEW

**Comment by mateusfreira** [comment]
+1 it is very useful

**Comment by rhaylander** [comment]
+1

**Comment by cosmicanant** [comment]
Visitor Call back seems to be a useful feature. But don't you think that instead of applying visitor function on each level, You should have applied it to the actual object which is modified.
eg:  If we take same callback as in your previous comment, then consider following:
var a = { 'a1' : { a11 : 'old value'  } };
var b = { 'a1' : { a11 : 'updated value'}};
diffOb = diff.getDiff( a, b) ;
var c =  diff.applyDiff(a, diffOb, callBack) ;
c = {__visited: true, a1 : {  a11: 'oldValue' } }

Instead of above resulting data (c), I think the __visited must be applied to last key as below: 
c = { a1 : {a11 : 'updatedValue' , __visited: true} }
and In this way, we exactly know which part of the object is actually updated.  What you say ?

**Comment by IsabellaCerbino** [comment]
The idea isn't know which part of the object is actually updated. I need to know the path of the object modified.

e.g

``` javascript
var a = { 'a1' : { 'a11' : { 'a111' : 'old value'} } };
var b = { 'a1' : { 'a11' : {'a111' : 'updated value' } } };
diffOb = diff.getDiff( a, b) ;
var c = diff.applyDiff(a, diffOb, callBack) ;

//I need a 'c' value like:
c = {
    '__isVisited' : true,
    'a1' : {
        '__isVisited' : true,
        'a11' : {
            '__isVisited' : true,
            'a111' : 'old value'
        }
    }
}
```

In my case i use this library for visual objects and i need redraw all elements in the path of the modified object

**Comment by cosmicanant** [comment]
ok, Looks nice ! I will pull your changes. thank you for your contribution.

**Pull request merged**
